[package]
name = "rustroad"
version = "0.1.0"
authors = ["shiguera <shiguera@mercatorlab.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# float-cmp = "0.8"
